server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "sonicpro" # Set a secure password
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false

metrics:
  prometheus:
    enabled: false

s3:
  enabled: false

logging:
  file: application.log
